<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE qalab [<!ELEMENT qalab (summary,file*)>
<!ATTLIST qalab version CDATA #REQUIRED>
<!ELEMENT summary (summaryresult*)>
<!ELEMENT file (result+)>
<!ATTLIST file id ID #REQUIRED>
<!ATTLIST file path CDATA #REQUIRED>
<!ELEMENT result EMPTY>
<!ATTLIST result date CDATA #REQUIRED>
<!ATTLIST result statvalue CDATA #REQUIRED>
<!ATTLIST result type CDATA #REQUIRED>
<!ELEMENT summaryresult EMPTY>
<!ATTLIST summaryresult date CDATA #REQUIRED>
<!ATTLIST summaryresult statvalue CDATA #REQUIRED>
<!ATTLIST summaryresult filecount CDATA #REQUIRED>
<!ATTLIST summaryresult type CDATA #REQUIRED>
]>
<qalab version="1.1">
    <summary>
        <summaryresult date="2019-09-17" filecount="7" statvalue="1525" type="checkstyle"/>
        <summaryresult date="2019-09-17" filecount="7" statvalue="131" type="pmd"/>
        <summaryresult date="2019-09-18" filecount="7" statvalue="1525" type="checkstyle"/>
        <summaryresult date="2019-09-18" filecount="7" statvalue="131" type="pmd"/>
        <summaryresult date="2019-09-20" filecount="7" statvalue="1525" type="checkstyle"/>
        <summaryresult date="2019-09-20" filecount="7" statvalue="131" type="pmd"/>
    </summary>
    <file id="ca_etsmtl_log240_financej_Account.java" path="ca/etsmtl/log240/financej/Account.java">
        <result date="2019-09-17" statvalue="507" type="checkstyle"/>
        <result date="2019-09-17" statvalue="17" type="pmd"/>
        <result date="2019-09-18" statvalue="507" type="checkstyle"/>
        <result date="2019-09-18" statvalue="17" type="pmd"/>
        <result date="2019-09-20" statvalue="507" type="checkstyle"/>
        <result date="2019-09-20" statvalue="17" type="pmd"/>
    </file>
    <file id="ca_etsmtl_log240_financej_App.java" path="ca/etsmtl/log240/financej/App.java">
        <result date="2019-09-17" statvalue="10" type="checkstyle"/>
        <result date="2019-09-17" statvalue="1" type="pmd"/>
        <result date="2019-09-18" statvalue="10" type="checkstyle"/>
        <result date="2019-09-18" statvalue="1" type="pmd"/>
        <result date="2019-09-20" statvalue="10" type="checkstyle"/>
        <result date="2019-09-20" statvalue="1" type="pmd"/>
    </file>
    <file id="ca_etsmtl_log240_financej_Category.java" path="ca/etsmtl/log240/financej/Category.java">
        <result date="2019-09-17" statvalue="178" type="checkstyle"/>
        <result date="2019-09-17" statvalue="18" type="pmd"/>
        <result date="2019-09-18" statvalue="178" type="checkstyle"/>
        <result date="2019-09-18" statvalue="18" type="pmd"/>
        <result date="2019-09-20" statvalue="178" type="checkstyle"/>
        <result date="2019-09-20" statvalue="18" type="pmd"/>
    </file>
    <file id="ca_etsmtl_log240_financej_DBUtils.java" path="ca/etsmtl/log240/financej/DBUtils.java">
        <result date="2019-09-17" statvalue="45" type="checkstyle"/>
        <result date="2019-09-17" statvalue="19" type="pmd"/>
        <result date="2019-09-18" statvalue="45" type="checkstyle"/>
        <result date="2019-09-18" statvalue="19" type="pmd"/>
        <result date="2019-09-20" statvalue="45" type="checkstyle"/>
        <result date="2019-09-20" statvalue="19" type="pmd"/>
    </file>
    <file id="ca_etsmtl_log240_financej_FinanceJ.java" path="ca/etsmtl/log240/financej/FinanceJ.java">
        <result date="2019-09-17" statvalue="236" type="checkstyle"/>
        <result date="2019-09-17" statvalue="26" type="pmd"/>
        <result date="2019-09-18" statvalue="236" type="checkstyle"/>
        <result date="2019-09-18" statvalue="26" type="pmd"/>
        <result date="2019-09-20" statvalue="236" type="checkstyle"/>
        <result date="2019-09-20" statvalue="26" type="pmd"/>
    </file>
    <file id="ca_etsmtl_log240_financej_Ledger.java" path="ca/etsmtl/log240/financej/Ledger.java">
        <result date="2019-09-17" statvalue="349" type="checkstyle"/>
        <result date="2019-09-17" statvalue="29" type="pmd"/>
        <result date="2019-09-18" statvalue="349" type="checkstyle"/>
        <result date="2019-09-18" statvalue="29" type="pmd"/>
        <result date="2019-09-20" statvalue="349" type="checkstyle"/>
        <result date="2019-09-20" statvalue="29" type="pmd"/>
    </file>
    <file id="ca_etsmtl_log240_financej_Reports.java" path="ca/etsmtl/log240/financej/Reports.java">
        <result date="2019-09-17" statvalue="200" type="checkstyle"/>
        <result date="2019-09-17" statvalue="21" type="pmd"/>
        <result date="2019-09-18" statvalue="200" type="checkstyle"/>
        <result date="2019-09-18" statvalue="21" type="pmd"/>
        <result date="2019-09-20" statvalue="200" type="checkstyle"/>
        <result date="2019-09-20" statvalue="21" type="pmd"/>
    </file>
</qalab>
